### ISSUE TITLE
CovePop close window issue

### ISSUE THREAD

**Issue by sheela42** [tylerpearson/CoverPop#16]
I am having an issue with CoverPop close window.  Can anyone help with me this issue ?

The html CoverPop code is in the body tag at the top. I have added the javascript code and call to plugin before the closing </body> tag.

The window pops-up with the Donate button and Close this window link. When I click "Close this window" link nothing happens but I see a hash appended to the url but the window does not close.

<html class="CoverPop-open">
<body>

    
    <div id="CoverPop-cover" class="splash">
        <div class="CoverPop-content splash-center">
                    
            
            <h2 class="splash-title">Welcome to Parachute</h2>
            <p class="splash-intro">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.</p>
            <a class="donate CoverPop-close-go" href="https://donate.parachutecanada.org">DONATE NOW!</a> or
            <a class ="CoverPop-close" href="#">Close this window</a>
                    
        </div>
    </div>
    <br />

<script type="text/javascript" src="/js/libs/CoverPop.js"></script>

<script>CoverPop.start({debug:true});</script>
</body>
</html>

**Comment by samford** [comment]
This has been discussed in issue #7, so if you haven't gone through that thread then you might find some insight there.  In particular, I provided an [explanation of the issue's cause as well as a workaround](https://github.com/tylerpearson/CoverPop/issues/7#issuecomment-74949289) that resolves it, so I would take a look at that and make sure your code conforms.

If you're still having issues after going through that thread (or if your page was already set up as I described) then please expand the code snippet to include where you're adding the CoverPop JavaScript file and executing `CoverPop.start()`.

**Comment by sheela42** [comment]
The js file and the call to plugin is moved below the Cover Pop Html.  I also modified the code snippet in the CoverPop.js file as indicated by moving it to inside the CoverPop.init function but I am still unable to close the window !

http://www.parachutecanada.org/home/newhome#

If you click on the above url you will see what I mean.  Thanks so much for responding :)

**Comment by samford** [comment]
The "Close this window" button worked fine for me on the initial page load but the issue that I'm seeing is that your popover appears on every page load, even after the cookie is set.

You seem to have manually set the "CoverPop-open" class on your HTML element and this is why CoverPop is displaying even when it shouldn't be.  CoverPop adds that class itself when it runs, so you shouldn't be adding that manually and if you remove it then it should resolve your issue.

What's happening here is that the popover technically shouldn't be displaying but since that "CoverPop-open" class is always there it always displays.  CoverPop *thinks* that the popover isn't being displayed so it doesn't bother doing things like binding the close button and that's why it seems like your close button isn't working.

Hopefully this solves your problem but if it doesn't then let me know.

**Comment by sheela42** [comment]
Thanks again.  I removed the CoverPop-open class on the HTML and now the pop-up does not appear at all.  Not sure what is going on...

http://www.parachutecanada.org/home/newhome

**Comment by samford** [comment]
CoverPop is acting appropriately here; the popover's not showing because the `_CoverPop` cookie is set.  You'll need to clear that cookie from your browser to see the popover again.

**Comment by sheela42** [comment]
Thank you so much Sam !  I am going to bother you with one more question.  Would this window appear on ANY of the page the user landed the first time ?  I am still testing this on a separate template.  This is currently not live but what we want to do is for the window to appear on any page if the user lands the first time on the site.

**Comment by samford** [comment]
To have the CoverPop popover appear on any page you'll just need to make sure that:

1. The CoverPop HTML is present on the page.
2. The CoverPop JavaScript file is loaded on that page (ideally, after the CoverPop HTML, just to be safe).
3. The call to `CoverPop.start()` appears on that page (after the CoverPop HTML and the CoverPop JS file is loaded).

As long as you meet those requirements the popover will load as long as the cookie isn't set.  Once the cookie has been set the popover won't display until the cookie expires (the default is 30 days) or it's otherwise removed.

**Comment by sheela42** [comment]
Thank you so much Sam !  I am going to test this on the live site next week.  Appreciate all the help.

**Comment by samford** [comment]
I'm glad it was helpful.  Good luck!
