### ISSUE TITLE
Can't close popup

### ISSUE THREAD

**Issue by lburton2** [tylerpearson/CoverPop#7]
Hi! I just set up CoverPop on my Shopify site (super straightforward, thank you for the great features and documentation!) and I am trying to use a link to close the popup window like this: 

```

<a class="CoverPop-close" href="#">No Thanks</a>

```

When I inspect the element, it shows that the link has that class, but when I click it, nothing happens. Is there something I need to add to the CoverPop.js or to my markup that will activate the close function?

Thanks!

**Comment by ksinget** [comment]
Hi Tyler!
Great plugin, exactly what I was looking for, thanks so much for sharing.

I too am having the exact same issue this user is. Not sure if they have gotten it resolved. My popup appears fine and then I have two buttons:
<a class="CoverPop-close" href="anotherlink.aspx">Another Page Link</a>
and
<a class="CoverPop-close" href="#">Continue to site</a>

The "Continue to site" button does nothing. If I click the other page link, I do go there, but if I go back to home again the popup appears (so the cookie hasnt worked for that button either). The only thing that does work is pressing 'Esc' and then the popup box wont appear again (cookies working). 

I even tried copying and pasting your demo to be sure (the html and the coverpop.js link). Same thing, the # link doesn't close it.

I'm sure I must have missed something, any help you can provide is greatly appreciated!

**Comment by cowboysdude** [comment]
Yes I see no answer for this LOL I'm having the same issue.  I guess while I'm at it.. is it possible to close it with a mouse click?

**Comment by samford** [comment]
I came across this issue as well but I was able to work around it by setting everything up in a certain way.

From what I've seen, if the CoverPop HTML comes somewhere after where the CoverPop JavaScript file is loaded then those `.CoverPop-close` elements won't be bound to the close event.  [Note that this is related to where the CoverPop JS _file_ is loaded, not where the `CoverPop.start()` call occurs.]

For example, if you did something naughty like load CoverPop.min.js in the head then you would have this issue:

```html
<html>
  <head>
    <script type="text/javascript" src="CoverPop.min.js"></script>
  </head>
  <body>
    <div id="CoverPop-cover" class="splash">
      <div class="CoverPop-content splash-center">
        <!-- the popup content (form, welcome message, etc.) -->
        <a class="CoverPop-close" href="#">or skip signup</a>
      </div><!--end .splash-center -->
    </div><!--end .splash -->

    <script type="text/javascript">
      CoverPop.start();
    </script>
  </body>
</html>
```

However, if you loaded CoverPop.min.js at the end of the body and had the CoverPop HTML somewhere above it then it would work fine:

```html
<html>
  <body>
    <div id="CoverPop-cover" class="splash">
      <div class="CoverPop-content splash-center">
        <!-- the popup content (form, welcome message, etc.) -->
        <a class="CoverPop-close" href="#">or skip signup</a>
      </div><!--end .splash-center -->
    </div><!--end .splash -->

    <script type="text/javascript" src="CoverPop.min.js"></script>
    <script type="text/javascript">
      CoverPop.start();
    </script>
  </body>
</html>
```

I initially ran into this issue because I was dynamically adding the CoverPop HTML _after_ the CoverPop JS was loaded (so the CoverPop HTML didn't exist before the CoverPop JS was loaded).  When I modified this setup to load the CoverPop JS after the code to add the CoverPop HTML it worked as expected.


At least from a cursory glance (and correct me if I'm wrong), this seems to be because the elements with the CoverPop-close class are determined when the CoverPop JS file is loaded, not when `CoverPop.start()` is called.  To test this, I modified the CoverPop.js file to have the `$el` definition in `CoverPop.init()` (keeping the original `$el` declaration where it was) and the binding works correctly in the aforementioned problem scenarios.  With this modification you would only have to make sure that the call to `CoverPop.start()` is after the CoverPop HTML (not the entire CoverPop JS file).

Anyway, I hope this helps to mitigate/resolve the issue.  Thanks for the plugin!

**Comment by erichomanchuk** [comment]
Also because of when the elements are fetched when the file is loaded it makes it impossible to specify a different ID or class for any of the elements because there not fetched on initialization. I had to modify the source to get this to work at all.  I updated the code as per @samford suggestion to get my own unique ids or classes to work.

**Comment by cowboysdude** [comment]
Figured that out and got it to work!! Many Thanks for all your work!!

**Comment by samford** [comment]
@erichomanchuk is right about this affecting the ability to effectively customize the id and class names.  The `mergeObj` function isn't run until `CoverPop.init()` is executed, so some of those user-provided settings don't end up getting used like they should.

I'm going to go ahead and create another issue for this and reference this one.
